name: CI

on: 
  push:
    branches:
      - master
      - linux-build-fixes # Temporary branch for Linux build fixes

env:
  PROJECT_VERSION_PATCH: 1

  VCPKG_CACHE_DIR: "${{ github.workspace }}/vcpkg-cache"
  VCPKG_BUILD_TYPE: release
  VCPKG_BINARY_SOURCES: "clear;files,${{ github.workspace }}/vcpkg-cache,readwrite"

jobs:
  build_compressonator_linux:
    runs-on: ubuntu-latest
    name: "Build CLI and Libraries (Linux)"
    container: ghcr.io/iamsomeone2/compressonator-builder:fedora42

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 1
      
      - name: Create Build directory
        run: mkdir cmake-build

      - name: Configure CMake
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        run: cmake --preset=linux_ci_build -DPROJECT_VERSION_PATCH=$PROJECT_VERSION_PATCH

      - name: Build
        run: cmake --build cmake-build

      - name: Bundle artifacts
        run: |
          mkdir -p cmake-build/out && \
          rm cmake-build/lib/libgtest.a && \
          mv cmake-build/bin cmake-build/out/ && \
          mv cmake-build/lib cmake-build/out/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with: 
            name: Compressonator_Linux-${{ runner.arch }}_${{ github.ref_name }}_Build
            path: cmake-build/out
              

  build_compressonator_windows:
    runs-on: windows-latest
    name: "Build CLI and Libraries (Windows)"

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 1

      - name: Create vcpkg cache directory
        run: mkdir ${{ env.VCPKG_CACHE_DIR }}

      - uses: actions/cache@v4
        name: Cache vcpkg
        with:
          path: ${{ env.VCPKG_CACHE_DIR }}
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-
          
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Create build directory
        run: mkdir cmake-build

      - name: Configure CMake
        run: cmake --preset=windows_ci_build -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT\\scripts\\buildsystems\\vcpkg.cmake" -DPROJECT_VERSION_PATCH=$PROJECT_VERSION_PATCH

      - name: Build
        run: cmake --build cmake-build

      - name: Bundle artifacts
        run: |
          mkdir -p cmake-build/out && \
          rm cmake-build/lib/libgtest.a && \
          mv cmake-build/bin cmake-build/out/ && \
          mv cmake-build/lib cmake-build/out/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Compressonator_Windows-${{ runner.arch }}_${{ github.ref_name }}_Build
          path: cmake-build/out

      #   build_compressonator_framework:
#     runs-on: windows-latest

#     steps:
#       - uses: actions/checkout@v4
#         with:
#           submodules: true
#           fetch-depth: 1

#       - name: Create Build Environment
#         # Some projects don't allow in-source building, so create a separate build directory
#         # We'll use this as our working directory for all subsequent commands
#         run: cmake -E make_directory ${{github.workspace}}/build/bin
      
# #      - name: Sync external libs
# #        working-directory: ${{github.workspace}}/build/
# #        run: python fetch_dependencies.py
      
#       - name: Add msbuild to PATH
#         uses: microsoft/setup-msbuild@v1.1

#       - name: Build Framework Release Win32
#         run: 'msbuild -target:build -property:Configuration=Release -property:Platform=Win32 -m build_sdk\cmp_framework.sln'

#       - name: Build Framework Debug Win32
#         run: 'msbuild -target:build -property:Configuration=Debug -property:Platform=Win32 -m build_sdk\cmp_framework.sln'

#       - name: Build Framework Release x64
#         run: 'msbuild -target:build -property:Configuration=Release -property:Platform=x64 -m build_sdk\cmp_framework.sln'
      
#       - name: Build Framework Debug x64
#         run: 'msbuild -target:build -property:Configuration=Debug -property:Platform=x64 -m build_sdk\cmp_framework.sln'

#       - name: Build Framework Release_MD Win32
#         run: 'msbuild -target:build -property:Configuration=Release_MD -property:Platform=Win32 -m build_sdk\cmp_framework.sln'

#       - name: Build Framework Debug_MD Win32
#         run: 'msbuild -target:build -property:Configuration=Debug_MD -property:Platform=Win32 -m build_sdk\cmp_framework.sln'

#       - name: Build Framework Release_MD x64
#         run: 'msbuild -target:build -property:Configuration=Release_MD -property:Platform=x64 -m build_sdk\cmp_framework.sln'

#       - name: Build Framework Debug_MD x64
#         run: 'msbuild -target:build -property:Configuration=Debug_MD -property:Platform=x64 -m build_sdk\cmp_framework.sln'

#       - name: Build Framework Release_DLL Win32
#         run: 'msbuild -target:build -property:Configuration=Release_DLL -property:Platform=Win32 -m build_sdk\cmp_framework.sln'

#       - name: Build Framework Debug_DLL Win32
#         run: 'msbuild -target:build -property:Configuration=Debug_DLL -property:Platform=Win32 -m build_sdk\cmp_framework.sln'

#       - name: Build Framework Release_DLL x64
#         run: 'msbuild -target:build -property:Configuration=Release_DLL -property:Platform=x64 -m build_sdk\cmp_framework.sln'

#       - name: Build Framework Debug_DLL x64
#         run: 'msbuild -target:build -property:Configuration=Debug_DLL -property:Platform=x64 -m build_sdk\cmp_framework.sln'

#       - name: Build Framework Release_MD_DLL Win32
#         run: 'msbuild -target:build -property:Configuration=Release_MD_DLL -property:Platform=Win32 -m build_sdk\cmp_framework.sln'

#       - name: Build Framework Debug_MD_DLL Win32
#         run: 'msbuild -target:build -property:Configuration=Debug_MD_DLL -property:Platform=Win32 -m build_sdk\cmp_framework.sln'

#       - name: Build Framework Release_MD_DLL x64
#         run: 'msbuild -target:build -property:Configuration=Release_MD_DLL -property:Platform=x64 -m build_sdk\cmp_framework.sln'

#       - name: Build Framework Debug_MD_DLL x64
#         run: 'msbuild -target:build -property:Configuration=Debug_MD_DLL -property:Platform=x64 -m build_sdk\cmp_framework.sln'

#       - name: Create folder structure for build results
#         run: |
#           mkdir CompressonatorFramework_result\lib\encoders
#           mkdir CompressonatorFramework_result\include
#           mkdir CompressonatorFramework_result\lib\build_sdk\x64
#           mkdir CompressonatorFramework_result\lib\build_sdk\x86

#       - name: Copy files into build results directory
#         shell: bash
#         run: |
#           cp build/Release*/x64/{*.lib,*.dll} CompressonatorFramework_result/lib/build_sdk/x64/
#           cp build/Release*/Win32/{*.lib,*.dll} CompressonatorFramework_result/lib/build_sdk/x86/
#           cp build/Debug*/x64/{*.lib,*.dll} CompressonatorFramework_result/lib/build_sdk/x64/
#           cp build/Debug*/Win32/{*.lib,*.dll} CompressonatorFramework_result/lib/build_sdk/x86/
#           cp build/Release/x64/Plugins/Compute/{*.h,*.hlsl,*.cpp} CompressonatorFramework_result/lib/encoders/
#           cp cmp_compressonatorlib/compressonator.h CompressonatorFramework_result/include/

#       # Will probably want to collect the files into a better structure before running this command
#       - name: Upload Build Artifacts
#         uses: actions/upload-artifact@v4
#         with: 
#           name: CompressonatorFramework_Windows_Master_Build
#           path: CompressonatorFramework_result/
